//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicalInstrument.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Music_Instrument
    {
        public string InstrumentCode { get; set; }
        public string InstrumentName { get; set; }
        public string Description { get; set; }
        public byte[] InputDate { get; set; }
    }
}
